# Generated by Django 6.1.1 on 2026-09-08 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_score', models.FloatField(default=0.0, help_text='0-100 evidence-based credibility score')),
                ('consistency_score', models.FloatField(default=0.0, help_text='0-100 internal consistency of claims')),
                ('verdict', models.CharField(choices=[('credible', 'Credible'), ('needs_review', 'Needs Review'), ('suspicious', 'Suspicious')], default='needs_review', max_length=20)),
                ('ai_summary', models.TextField(blank=True, help_text='Hugging Face model output / explanation')),
                ('flags', models.JSONField(blank=True, default=list, help_text='List of specific red flags found')),
                ('model_used', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='candidates.resume')),
            ],
        ),
    ]
